### ISSUE TITLE
auth onclick(); is invalid. 

### ISSUE THREAD

**Issue by WilliamAnimate** [Gameplex-Software/gameplex-software.github.io#1]
![image](https://user-images.githubusercontent.com/75321465/148797927-30f57fb6-6e32-4821-9e7a-03369f516e2f.png)
**as im a ~~very good~~ no good programmer, im like how to fix this**

error at the code in line 234, column 91 to 103
[click here to see problem __**folder**__](https://github.com/Gameplex-Software/gameplex-software.github.io/tree/main/internal)
*note: it takes you to the folder/directory where the problem lies. let me know if you actually cant find it*

**Comment by tristanpoland** [comment]
Thank you  for the error report @WilliamAnimate, the issue was resolved with the following commit: https://github.com/Gameplex-Software/gameplex-software.github.io/commit/b147353e34224eceb2da36559b5578434c936a39 

Please note that since the login is scripted in the page the login is not yet secure, we will be locking it down on the self hosted site
